PROJECT = 'project_name'
REPOSITORY = 'repo.git'
VIRTUALENV = 'virtualenv_name'
ADDITIONAL_PACKAGES = []
ADDITIONAL_MANAGEMENT_COMMANDS = []

CI_KEY_FILENAME = 'key.pem'
CI_HOST = ''
CI_SETTINGS_PATH = ''

DEVELOPMENT_KEY_FILENAME = 'key.pem'
DEVELOPMENT_HOST = ''

STAGING_KEY_FILENAME = 'key.pem'
STAGING_HOST = ''

PRODUCTION_KEY_FILENAME = 'key.pem'
PRODUCTION_HOST = ''
